"""Add TimeSheet table

Revision ID: 0610b147e88f
Revises: fc2f0e7adaf2
Create Date: 2026-07-15 14:27:30.002392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0610b147e88f'
down_revision: Union[str, Sequence[str], None] = 'fc2f0e7adaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_sheet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('worked_days', sa.Float(), nullable=False),
    sa.Column('vacation_days', sa.Float(), nullable=False),
    sa.Column('sick_days', sa.Float(), nullable=False),
    sa.Column('sick_pay_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_sheet')
    # ### end Alembic commands ###
