"""Add currency columns to JournalLine

Revision ID: c5c80770cc09
Revises: 0610b147e88f
Create Date: 2026-07-15 14:29:25.019916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c80770cc09'
down_revision: Union[str, Sequence[str], None] = '0610b147e88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_line', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('journal_line', sa.Column('amount_currency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_line', 'amount_currency')
    op.drop_column('journal_line', 'currency')
    # ### end Alembic commands ###
