"""Add Warehouse and StockBatch models

Revision ID: f46536063ef7
Revises: c5c80770cc09
Create Date: 2026-07-15 14:34:54.549947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46536063ef7'
down_revision: Union[str, Sequence[str], None] = 'c5c80770cc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('original_qty', sa.BigInteger(), nullable=False),
    sa.Column('remaining_qty', sa.BigInteger(), nullable=False),
    sa.Column('unit_cost_minor', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company', sa.Column('inventory_method', sa.String(length=10), nullable=False, server_default='average'))
    op.add_column('stock_move', sa.Column('warehouse_id', sa.String(length=36), nullable=True))
    # op.create_foreign_key(None, 'stock_move', 'warehouse', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'stock_move', type_='foreignkey')
    op.drop_column('stock_move', 'warehouse_id')
    op.drop_column('company', 'inventory_method')
    op.drop_table('stock_batch')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
